# invocacion al action default para mostar datos de ejemplo
/dev:
    class: Curso
    action: default

/set/user/section:
    class: Curso
    action: setUserSection
    method: POST

/set/user/resource:
    class: Curso
    action: setUserResource
    method: POST

/set/user/course/sections:
    class: Curso
    action: getSectionsCourses
    method: POST

/get/courses/like/name:
    class: Curso
    action: getCoursesByName
    method: POST